language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="8dc85059-c0ec-43ba-9faf-6191b0bf101d"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - tamaosaridzawa9@gmail.com
    on_success: never # default: change
    on_failure: always # default: always